import { BountyProps } from "../bounty/bounty-card"
import { OrganizationProps } from "../creator/organization-card"
import { PlotProps } from "../plot/plot-card"

export const bounties: BountyProps[] = [
    {
        id: "b1",
        title: "Digital Land Survey",
        description: "Complete a digital survey of your plot and earn rewards.",
        type: "regular",
        reward: "$500",
        participants: 45,
        maxParticipants: 100,
        deadline: "May 30, 2025",
        image: "/images/location-pin.jpeg",
        featured: true,
    },
    {
        id: "b2",
        title: "Tech Valley Exploration",
        description: "Visit Tech Valley and complete location-based tasks.",
        type: "location",
        reward: "$750",
        participants: 28,
        location: "Tech Valley, Block A",
        deadline: "June 15, 2025",
        image: "/images/plot-sign.jpeg",
    },
    {
        id: "b3",
        title: "Green Haven Hunt",
        description: "Find all 5 checkpoints in the Green Haven development.",
        type: "scavenger",
        reward: "$1,000",
        participants: 12,
        maxParticipants: 50,
        location: "Green Haven",
        deadline: "July 1, 2025",
        image: "/images/plot-sale.jpeg",
    },
    {
        id: "b4",
        title: "Community Cleanup",
        description: "Join our community cleanup event and earn rewards.",
        type: "regular",
        reward: "$300",
        participants: 67,
        maxParticipants: 100,
        deadline: "May 25, 2025",
        image: "/images/location-pin.jpeg",
    },
    {
        id: "b5",
        title: "Innovation Corner Challenge",
        description: "Complete tasks at Innovation Corner for exclusive rewards.",
        type: "location",
        reward: "$600",
        participants: 34,
        location: "Innovation Corner",
        deadline: "June 10, 2025",
        image: "/images/plot-sign.jpeg",
        featured: true,
    },
    {
        id: "b6",
        title: "Digital Treasure Hunt",
        description: "Find digital treasures hidden across our developments.",
        type: "scavenger",
        reward: "$1,200",
        participants: 23,
        maxParticipants: 30,
        deadline: "July 15, 2025",
        image: "/images/plot-sale.jpeg",
    },
]

export const organizations: OrganizationProps[] = [
    {
        id: "o1",
        name: "Tech Valley Association",
        description: "Community of tech enthusiasts and property owners in Tech Valley.",
        members: 245,
        activeBounties: 5,
        location: "Tech Valley",
        logo: "/images/location-pin.jpeg",
        featured: true,
    },
    {
        id: "o2",
        name: "Green Haven Community",
        description: "Eco-conscious property owners focused on sustainable development.",
        members: 178,
        activeBounties: 3,
        location: "Green Haven",
        logo: "/images/plot-sale.jpeg",
    },
    {
        id: "o3",
        name: "Innovation Corner Hub",
        description: "Business owners and entrepreneurs at Innovation Corner.",
        members: 132,
        activeBounties: 4,
        location: "Innovation Corner",
        logo: "/images/plot-sign.jpeg",
    },
    {
        id: "o4",
        name: "Digital Landowners Guild",
        description: "Alliance of digital property investors across all developments.",
        members: 310,
        activeBounties: 7,
        location: "Multiple",
        logo: "/images/location-pin.jpeg",
        featured: true,
    },
    {
        id: "o5",
        name: "Future Builders Network",
        description: "Developers and architects planning the future of our communities.",
        members: 95,
        activeBounties: 2,
        location: "All Sectors",
        logo: "/images/plot-sign.jpeg",
    },
]

export const plots: PlotProps[] = [
    {
        id: "p1",
        title: "Tech Valley Plot",
        location: "North Sector, Block A",
        price: "$250,000",
        image: "/images/location-pin.jpeg",
        size: "500 sq.m",
        type: "Premium",
        featured: true,
    },
    {
        id: "p2",
        title: "Innovation Corner",
        location: "East Sector, Block C",
        price: "$320,000",
        image: "/images/plot-sign.jpeg",
        size: "650 sq.m",
        type: "Commercial",
    },
    {
        id: "p3",
        title: "Green Haven",
        location: "South Sector, Block D",
        price: "$280,000",
        image: "/images/plot-sale.jpeg",
        size: "550 sq.m",
        type: "Residential",
    },
    {
        id: "p4",
        title: "Digital Hub Plot",
        location: "West Sector, Block B",
        price: "$295,000",
        image: "/images/location-pin.jpeg",
        size: "580 sq.m",
        type: "Mixed Use",
        featured: true,
    },
    {
        id: "p5",
        title: "Eco Retreat",
        location: "South Sector, Block E",
        price: "$310,000",
        image: "/images/plot-sale.jpeg",
        size: "600 sq.m",
        type: "Residential",
    },
    {
        id: "p6",
        title: "Business Center Plot",
        location: "Central Sector, Block A",
        price: "$350,000",
        image: "/images/plot-sign.jpeg",
        size: "700 sq.m",
        type: "Commercial",
    },
]
